name: Publish to NuGet and GitHub Releases

on:
  push:
    branches:
      - master
      - dev

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          lfs: true

      - name: Install GitVersion
          uses: gittools/actions/gitversion/setup@v4.5.0
          with:
            versionSpec: '6.7.x'

      - name: Determine Version
          id: version_step
          uses: gittools/actions/gitversion/execute@v4.5.0
          with:
            configFilePath: GitVersion.yml
            disableCache: true
            updateAssemblyInfo: true
            updateProjectFiles: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore FmiSrl.FtpServer.Server/FmiSrl.FtpServer.Server.csproj

      - name: Build Project
        run: dotnet build FmiSrl.FtpServer.Server/FmiSrl.FtpServer.Server.csproj -c Release --no-restore

      - name: Pack NuGet Package
        run: dotnet pack FmiSrl.FtpServer.Server/FmiSrl.FtpServer.Server.csproj -c Release --no-build -o ./artifacts

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --skip-duplicate

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version_step.outputs.GitVersion_FullSemVer }}
          name: Release ${{ steps.version_step.outputs.GitVersion_FullSemVer }}
          generate_release_notes: true # Uses commit history for the changelog
          prerelease: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }} # Marks as pre-release if on 'dev'
          files: ./artifacts/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to NuGet.org
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
